apiVersion: v1
kind: Service
metadata:
  name: chat-api
  namespace: default
  labels:
    app: chat-api
spec:
  type: ClusterIP
  selector:
    app: chat-api
  ports:
    - port: 5666
      targetPort: 5666
      protocol: TCP
      name: websocket