kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../backend-base
- rollout-backend.yaml
- zabbix-agent-cm.yaml
- hpa.yaml

namespace: realchat
namePrefix: chatbackend-

configMapGenerator:
- name: cm
  envs: [application.properties]

secretGenerator:
- name: db-secret
  envs:
  - secret.properties

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: chatbackend-img-env
      fieldPath: data.IMAGE_NAME
    targets:
    - select:
        kind: Rollout
      fieldPaths:
      - spec.template.spec.containers.[name=main].image
      options:
        delimiter: ':'
        index: 0
  - source:
      kind: ConfigMap
      name: chatbackend-img-env
      fieldPath: data.ZBX_IMAGE_NAME
    targets:
    - select:
        kind: Rollout
      fieldPaths:
      - spec.template.spec.containers.[name=zabbix-agentd].image
      options:
        delimiter: ':'
        index: 0

patches:
  - target:
      kind: Rollout
      name: rollout
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
        value: /health
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
        value: /health
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 120
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 120
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "200Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"

  - target:
      kind: HorizontalPodAutoscaler
      name: hpa
    patch: |
      - op: replace
        path: /spec/scaleTargetRef/name
        value: chatbackend-rollout
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 4
      - op: replace
        path: /spec/behavior/scaleDown/stabilizationWindowSeconds
        value: 1200
      - op: replace
        path: /spec/behavior/scaleUp/stabilizationWindowSeconds
        value: 300

# images:
#   - name: image
#     newName: $(IMAGE_NAME)
#     newTag: $(IMAGE_TAG)
#   - name: zabbix-image
#     newName: $(ZBX_IMAGE_NAME)
#     newTag: $(ZBX_IMAGE_TAG)