{{- if .Values.zabbixWebService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-webservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
    app.kubernetes.io/component: webservice
    {{- if .Values.zabbixWebService.extraDeploymentLabels }}
    {{- toYaml .Values.zabbixWebService.extraDeploymentLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key,$value := .Values.zabbixWebService.extraDeploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.zabbixWebService.replicaCount }}
  selector:
    matchLabels:
      {{- include "zabbix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webservice
  template:
    metadata:
      annotations:
        {{- range $key,$value := .Values.zabbixWebService.extraPodAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "zabbix.labels" . | nindent 8 }}
        app.kubernetes.io/component: webservice
        {{- if .Values.zabbixWebService.extraPodLabels }}
        {{- toYaml .Values.zabbixWebService.extraPodLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "zabbix.serviceAccountName" . }}
      {{- with .Values.zabbixWebService.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.zabbixWebService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.affinity) 0 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.zabbixWebService.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-webservice
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zabbixWebService.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: zabbix-webservice
        resources:
          {{- toYaml .Values.zabbixWebService.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.zabbixWebService.securityContext | nindent 10 }}
        {{- if .Values.zabbixWebService.image.tag }}
        image: "{{ .Values.zabbixWebService.image.repository }}:{{ .Values.zabbixWebService.image.tag }}"
        {{- else }}
        image: "{{ .Values.zabbixWebService.image.repository }}:{{ .Values.zabbixImageTag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.zabbixWebService.image.pullPolicy }}
        env:
          {{- if .Values.zabbixWebService.ignoreURLCertErrors }}
          - name: ZBX_IGNOREURLCERTERRORS
            value: {{ .Values.zabbixWebService.ignoreURLCertErrors }}
          {{- end }}
          {{- with .Values.zabbixWebService.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - name: ZBX_ALLOWEDIP
            value: "::/0"
        ports:
          - name: webservice
            containerPort: 10053
            protocol: TCP
        {{- with .Values.zabbixWebService.extraVolumeMounts }}
        volumeMounts:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.zabbixWebService.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.zabbixWebService.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.zabbixWebService.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.zabbixWebService.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixWeb.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- with .Values.zabbixWebService.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
