{{ if and .Values.zabbixServer.enabled .Values.zabbixServer.zabbixServerHA.enabled }}
{{ if and .Values.zabbixServer.zabbixServerHA.enabled .Values.postgresql.enabled }}
{{ fail "We do not support enabling Zabbix Server native High Availability combined with `postgresql.enabled=true`. Please bring your own database to use Zabbix Server HA!" }}
{{ end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "zabbix.fullname" . }}-create-upgrade-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
    app.kubernetes.io/component: create-upgrade-db
    {{- if .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.jobLabels }}
    {{- toYaml .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.jobLabels | nindent 6 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- range $key,$value := .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.jobAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      {{- with .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.zabbixServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      {{- if .Release.IsUpgrade }}
      serviceAccountName: {{ template "zabbix.fullname" . }}-ha-helper
      {{- end }}
      containers:
        {{- with .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      - name: create-upgrade-db
        {{- $pattern := "[0-9]+\\.[0-9]+" -}}
        {{- $tag := "" -}}
        {{- if .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.tag }}
          {{- $tag = .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.tag }}
        {{- else if .Values.zabbixServer.image.tag }}
          {{- $zabbixTag := .Values.zabbixServer.image.tag -}}
          {{- $match := regexFind $pattern $zabbixTag -}}
          {{- if $match }}
            {{- $tag = printf "%s-%s" $match .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.tagSuffix -}}
          {{- end }}
        {{- else }}
          {{- $globalTag := .Values.zabbixImageTag -}}
          {{- $match := regexFind $pattern $globalTag -}}
          {{- if $match }}
            {{- $tag = printf "%s-%s" $match .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.tagSuffix -}}
          {{- end }}
        {{- end }}
        {{- if eq $tag "" }}
          {{- fail "Failed to generate tag: Ensure the input values match the expected pattern." -}}
        {{- else }}
        image: "{{ .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.repository }}:{{ $tag }}"
        {{- end }}
        {{- if .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.pullPolicy }}
        imagePullPolicy: {{ .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.image.pullPolicy }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.resources | nindent 10 }}
        env:
          - name: ZBX_SERVER_DEPLOYMENT_NAME
            value: {{ template "zabbix.fullname" . }}-zabbix-server
          - name: HELM_HOOK_TYPE
            {{- if .Release.IsUpgrade }}
            value: upgrade
            {{- else if .Release.IsInstall }}
            value: install
            {{- else }}
            value: unknown
            {{- end }}
          {{- include "zabbix.postgresAccess.variables" (list $ . "db_init_upgrade") | nindent 10 }}
          {{- with .Values.zabbixServer.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        args:
          - init_and_upgrade_db
      imagePullSecrets:
      {{- range .Values.zabbixServer.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      restartPolicy: Never
      {{- with .Values.zabbixServer.zabbixServerHA.dbCreateUpgradeJob.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
