{{ if and .Values.zabbixServer.enabled .Values.zabbixServer.zabbixServerHA.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "zabbix.fullname" . }}-ha-helper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
  {{- if .Values.zabbixServer.zabbixServerHA.roleBinding.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.zabbixServerHA.roleBinding.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "zabbix.serviceAccountName" . }}
- kind: ServiceAccount
  name: {{ template "zabbix.fullname" . }}-ha-helper
roleRef:
  kind: Role
  name: {{ template "zabbix.fullname" . }}-ha-helper
  apiGroup: rbac.authorization.k8s.io
{{ end }}
