{{ if and .Values.zabbixServer.enabled .Values.zabbixServer.zabbixServerHA.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zabbix.fullname" . }}-ha-helper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
  {{- if .Values.zabbixServer.zabbixServerHA.serviceAccount.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.zabbixServerHA.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{ end }}
