version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: my_redis
    command: redis-server --requirepass Blud1234567
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=Blud1234567
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  redis_data:
  rabbitmq_data: