apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
    AWS_REGION: "ap-northeast-2"
    AWS_ACCESS_KEY_ID: "AKIATCKANWP6OMLSDJVO"
    AWS_SECRET_ACCESS_KEY: "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"