apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: chatbackend
  ports:
  - protocol: TCP
    port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  selector:
    app: chatbackend
  ports:
  - protocol: TCP
    port: 3000
