nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/template/spec/containers/envFrom/configMapRef/name
    kind: Rollout
  - path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
    kind: Rollout
  - path: spec/template/spec/volumes/configMap/name
    kind: Rollout
  - path: spec/template/spec/initContainers/env/valueFrom/configMapKeyRef/name
    kind: Rollout
- kind: Service
  version: v1
  fieldSpecs:
  - path: spec/strategy/blueGreen/activeService
    kind: Rollout
  - path: spec/strategy/blueGreen/previewService
    kind: Rollout
  - path: spec/rules/http/paths/backend/service/name
    kind: Ingress

commonLabels:
- path: metadata/labels
  create: true

- path: spec/selector
  create: true
  version: v1
  kind: Service

- path: spec/selector/matchLabels
  create: true
  kind: Deployment