apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  strategy:
    blueGreen:
      activeService: service
      previewService: green
      autoPromotionEnabled: false
  replicas: 1 # kustomize
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: topology.kubernetes.io/zone
      #     whenUnsatisfiable: DoNotSchedule
      #     labelSelector:
      #       app: chat-api
      initContainers:
        - name: wait-for-backend
          image: busybox:1.28
          command: 
          - sh
          - -c
          - |
            until nslookup $(echo $EXTERNAL_API_URL | cut -d/ -f3 | cut -d: -f1) && wget -O- -T 5 $EXTERNAL_API_URL/health; do 
              echo waiting for backend
              sleep 2
            done
          env:
          - name: EXTERNAL_API_URL
            valueFrom:
              configMapKeyRef:
                name: cm
                key: EXTERNAL_API_URL
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: 
          - sh
          - -c
          - |
            until nslookup ${RABBITMQ_NS} && nc -z ${RABBITMQ_NS} 5672; do
              echo waiting for rabbitmq
              sleep 2
            done
          env:
          - name: RABBITMQ_NS
            valueFrom:
              configMapKeyRef:
                name: cm
                key: RABBITMQ_NS
      containers:
      - name: main
        image: $(IMAGE_NAME)          #kustomize
        imagePullPolicy: Always
        resources:
          requests:
            memory: ""
            cpu: ""
          limits:
            memory: ""
            cpu: ""
        ports:
        - name: http
          containerPort: 5666
          protocol: TCP
        readinessProbe:       #kustomize
          httpGet:
            path: /
            port: 5666
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:      #kustomize
          httpGet:
            path: /
            port: 5666
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: cm            #kustomize
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SVCPOD
          valueFrom:
            configMapKeyRef:
              name: cm
              key: SVCPOD
        - name: LOG_PATH
          value: /data/logs/$(SVCPOD)/

        # Other environment variables as needed
        volumeMounts:
        - name : logs-pv
          mountPath: /data/logs
        # - name : backend-pv
        #   mountPath: /app/uploads
      
      - name: zabbix-agentd
        image: $(ZBX_IMAGE_NAME)
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "80m"
          limites:
            memory: "100Mi"
            cpu: "80m"
        volumeMounts:
        - name: zabbix-agent-cm
          mountPath: /etc/zabbix/

      terminationGracePeriodSeconds: 1000
      volumes:
      - name: logs-pv
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: chat-api-pv
        persistentVolumeClaim:
          claimName: chat-api-pvc
      - name: zabbix-agent-cm
        configMap:
          name: zabbix-agent-cm
