apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix-chatreal
  namespace: argocd
  labels:
    app: zabbix
    component: zabbix
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: default
  
  # Source configuration
  source:
    repoURL: git@github.com:thanhthanhha/chatreal.git
    targetRevision: HEAD  # or specify a branch/tag like 'main' or 'v1.0.0'
    path: k8s/advance/helm/zabbix
    
    # Helm-specific configuration
    helm:
      releaseName: realchat-zabbix
      # Values file override (optional)
      # valueFiles:
      #   - values.yaml
      #   - values-prod.yaml  # environment-specific values
  
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: realchat
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Revision history
  revisionHistoryLimit: 10
  
  # Health check configuration
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  
  # Blue-green or canary deployment (if using Argo Rollouts)
  # Uncomment if you want to use advanced deployment strategies
  # sources:
  #   - repoURL: git@github.com:thanhthanhha/chatreal.git
  #     targetRevision: HEAD
  #     path: k8s/advance/helm/zabbix
  #     helm:
  #       valueFiles:
  #         - values.yaml